language: node_js
sudo: false
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aw5YtM3mpeGndNUSA7HTFxj4G+7Pz8+BOnmaozrSrSEN8UKufHjRlVLRMSMrFetGxpnVWLAWVqIa5WClndsJjnJ4aNh3fnOOfRwD347Hx6Er1YecHHSEACiU3tUF1V4bb6Efkva70fk+tPdAjisFH9cu4Gl4n/MRQOYypjpWigU=
  file:
    - 'afinn-111.js'
    - 'afinn-111.min.js'
  on:
    tags: true
